name: Run Tests

on:
  push:
    branches: [main]

permissions:
  id-token: write
  pull-requests: write
  statuses: write
  actions: read
  contents: read

jobs:
  build:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: "us-east-1"
          audience: "sts.amazonaws.com"

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
            terraform_version: 1.1.9
      - name: Initialize
        run: terraform init
      - name: validate
        run: terraform validate
      - name: format
        run: terraform fmt -check
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test with pytest
        run: |
          pytest
        env:
          AWS_ROLE: ${{ secrets.AWS_ROLE }}

  